### ISSUE TITLE
Check validity and correct municipality of geometries

### ISSUE THREAD

**Issue by wkmor1** [luomus/crowdsorsa-etl#2]
Check to see if the geometries of the 2024 data are vaild and that they correspond to the municipality that has been indicated.

**Comment by AlpoTurunen** [comment]
There are a lot of polygons on the border of two municipalities without mentioning the other one: 

> tunniste / municipality in the dataset / another municipality
> 253839     Ulvila        Nakkila
> 253838     Ulvila        Nakkila
> 253843     Ulvila        Nakkila
> 230298   Helsinki         Vantaa
> 190823   Helsinki         Vantaa
> 193234   Helsinki         Vantaa
> 197488   Helsinki          Espoo
> 210837   Helsinki          Espoo
> 193491   Helsinki         Vantaa
> 188501   Helsinki          Espoo
> 220725   Helsinki          Espoo
> 220729   Helsinki          Espoo
> 189385   Helsinki          Espoo
> 188491   Helsinki          Espoo
> 232609  Järvenpää        Tuusula

And one without geometry. This can be discarded?:

> 216870    Tuusula  

Also, the data looks ugly but is basically ok:

![Image](https://github.com/user-attachments/assets/175a4f09-0063-4e5c-96c9-aab1858a72d9)

**Comment by wkmor1** [comment]
I think it should be ok that only one municipality is indicated in the raw data as long it is not far away from the geometry. The DW ETL process should handle adding the other municipality when it interprets the data.

**Comment by wkmor1** [comment]
Should we seek further clarification on what these polygons actually are? They look more like GPS tracks than areas of occurrence? @AlpoTurunen Maybe you could check how well they actually corresponed to the "pint.ala" column.

**Comment by AlpoTurunen** [comment]
Yes, they appear to be GPS trajectories that were automatically converted to polygons. For cleaner geometry, we could create bounding boxes around the geometries and use those instead. Not exactly the same, but does it matter? :) Also, most polygons are from the same area, so what if we merged them and used time periods instead of timestamps?

Regarding the 'Pinta-ala' column, the difference from the calculated areas was more than 1 square meter in 118 out of 11 444 cases.

**Comment by wkmor1** [comment]
In general we do not touch raw data. That is not our job as an aggregator. We can and do augment data via linking and interpretation and when necessary we obscure data (sensitive taxa etc). Before mobilising data we work with data provider to fix any errors.

How much more than 1m?

**Comment by AlpoTurunen** [comment]
Varies a lot. Would be interesting to hear how they calculated those values

![Image](https://github.com/user-attachments/assets/6f9782fb-1e38-48a8-b36d-878757354730)

**Comment by wkmor1** [comment]
OK. I will contact the data owner with our queries. You can close this task. Thanks
